image:
  - Visual Studio 2019
platform:
  - x64
configuration: Release

environment:
  Qt5_INSTALL_DIR: 'C:\Qt\5.14.2\msvc2019_64'
  PATH: '%Qt5_INSTALL_DIR%\bin;c:\msys64\usr\bin;%PATH%'

init:
  - set makefiles="NMake Makefiles"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%

before_build:
  - mkdir build
  - cd build

build_script:
  - cmake ..
  - nmake hashgen

artifacts:
  - path: bin/hashgen.exe
    name: binary