image:
  - Visual Studio 2019
platform:
  - x64
configuration: Release

environment:
  QT_DIR: C:\Qt\5.14\msvc2017_64

init:
  - set PATH=%QT_DIR%;%PATH%
  - set makefiles="NMake Makefiles"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%

before_build:
  - mkdir build
  - cd build

build_script:
  - cmake .. -DCMAKE_PREFIX_PATH=%QT_DIR%
  - devenv HashGenerator.sln /deploy Release
  - dir
  - dir bin
  - copy bin\Release\hashgen.exe %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: hashgen.exe
    name: hashgen_win_x64

deploy:
  release: hashgen_win_x64-v$(appveyor_build_version)
  description: 'Hash Generator'
  provider: GitHub
  auth_token:
    secure: oVwM4c3g2neQP4u9719kh6c76dYZfc/zrYc4gobomH3tWDP3m9eFeu0+ojh4VR68
  artifact: hashgen_win_x64
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true