image:
  - Visual Studio 2019
platform:
  - x64
configuration: Release

init:
  - set makefiles="NMake Makefiles"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%

before_build:
  - dir C:\Qt\5.14 /s /b /o:gn
  - mkdir build
  - cd build

build_script:
  - cmake .. -DCMAKE_PREFIX_PATH="%QTDIR%"
  - nmake hashgen

artifacts:
  - path: bin\hashgen.exe
    name: binary