language: cpp

stages:
  - build
  - test

addons:
  apt:
    update: true
    packages:
      - qt5-default
      - qtbase5-dev

  homebrew:
    update: true
    packages:
      - qt5

jobs:
  include:

    ###############################
    ##            TEST
    ###############################

    - stage: test
      os: linux
      dist: bionic
      language: cpp
      compiler: gcc
      install: &install_linux
        - wget https://github.com/Kitware/CMake/releases/download/v3.15.7/cmake-3.15.7-Linux-x86_64.tar.gz
        - tar -xf cmake-3.15.7-Linux-x86_64.tar.gz
        - export PATH=`pwd`/cmake-3.15.7-Linux-x86_64/bin:$PATH
      before_script: &before_script
        - mkdir build
        - cd build
      script: &script_test_linux
        - cmake ..
        - make hashgen_tests
        - ./bin/hashgen_tests

    - stage: test
      os: linux
      dist: bionic
      language: cpp
      compiler: clang
      install: *install_linux
      before_script: *before_script
      script: *script_test_linux

    - stage: test
      os: osx
      osx_image: xcode11.4
      language: cpp
      compiler: gcc
      install: &install_macos
        - wget https://github.com/Kitware/CMake/releases/download/v3.15.7/cmake-3.15.7-Darwin-x86_64.tar.gz
        - tar -xf cmake-3.15.7-Darwin-x86_64.tar.gz
        - export PATH=`pwd`/cmake-3.15.7-Darwin-x86_64/bin:$PATH
      before_script: &before_script_macos
        - brew link qt5
        - mkdir build
        - cd build
      script: &script_test_macos
        - cmake ..
        - make hashgen_tests
        - ./bin/hashgen_tests

    - stage: test
      os: osx
      osx_image: xcode11.4
      language: cpp
      compiler: clang
      install: *install_macos
      before_script: *before_script_macos
      script: *script_test_macos

    ###############################
    ##            BUILD
    ###############################
    - stage: build
      os: linux
      dist: bionic
      language: cpp
      compiler: gcc
      install: *install_linux
      before_script: *before_script
      script: &script_build_linux
        - cmake ..
        - make hashgen

    - stage: build
      os: linux
      dist: bionic
      language: cpp
      compiler: clang
      install: *install_linux
      before_script: *before_script
      script: *script_build_linux

    - stage: build
      os: osx
      osx_image: xcode11.4
      language: cpp
      compiler: gcc
      install: *install_macos
      before_script: *before_script_macos
      script: &script_build_macos
        - cmake ..
        - make hashgen

    - stage: build
      os: osx
      osx_image: xcode11.4
      language: cpp
      compiler: clang
      install: *install_macos
      before_script: *before_script_macos
      script: *script_build_macos